/**
 * Official NQR integration tests (NQR_INTEGRATION Phase 22).
 *
 * Covers: import parsing/validation/status classification, active-vs-expired
 * gating, explainable matching, eligibility/pathway filtering, provenance,
 * security invariants (RLS in the migration, no fabricated data), snapshot
 * integrity, and regression of the existing prototype pipeline.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { readXlsx, parseSharedStrings } from "../scripts/lib/nqr-xlsx.mjs";
import {
  normalizeRow,
  parseHours,
  parseOfficialDate,
  parseLevel,
  classifyStatus,
  contentHash,
  cleanText,
  isCurrentlyValidQualification,
  buildImportReport,
} from "../scripts/lib/nqr-normalize.mjs";
import {
  recommendNqrQualifications,
  scoreNqrQualification,
  NQR_SECTOR_MAP,
  type NqrQualification,
} from "../supabase/functions/_shared/nqrmatch";
import { recommendOpportunities } from "../supabase/functions/_shared/opportunity";
import { emptyProfile } from "../supabase/functions/_shared/extract";

const ROOT = process.cwd();
const migration = readFileSync(join(ROOT, "supabase", "nqr-migration.sql"), "utf8");
const importer = readFileSync(join(ROOT, "scripts", "nqr-import.mjs"), "utf8");
const dataLayer = readFileSync(join(ROOT, "src", "data", "nqr.ts"), "utf8");

// Real committed snapshot (generated by the importer from the official export).
const snapshotPath = join(ROOT, "public", "nqr", "official-active.json");
const snapshot = JSON.parse(readFileSync(snapshotPath, "utf8")) as {
  generated_at: string;
  source: string;
  source_note: string;
  count: number;
  records: Array<Record<string, unknown>>;
};

// ── Phase 22: import validation ────────────────────────────────────────────

describe("NQR field parsers (official export formats)", () => {
  it("parses official hour formats and rejects nonsense", () => {
    expect(parseHours("330 Hours")).toBe(330);
    expect(parseHours("4.5 Hours")).toBe(4.5);
    expect(parseHours("600")).toBe(600);
    expect(parseHours("N.A.")).toBeNull();
    expect(parseHours("")).toBeNull();
    expect(parseHours("abc Hours")).toBeNull();
    expect(parseHours("-5 Hours")).toBeNull();
    expect(parseHours("99999 Hours")).toBeNull();
  });

  it("parses official dates (dd Mon yyyy → ISO)", () => {
    expect(parseOfficialDate("17 Nov 2022")).toBe("2022-11-17");
    expect(parseOfficialDate("08 May 2025")).toBe("2025-05-08");
    expect(parseOfficialDate("1 Jan 2026")).toBe("2026-01-01");
    expect(parseOfficialDate("32 Dec 2025")).toBeNull();
    expect(parseOfficialDate("17 Foo 2022")).toBeNull();
    expect(parseOfficialDate("2022-11-17")).toBeNull();
  });

  it("preserves official NSQF display levels incl. half-levels; normalizes numerically", () => {
    expect(parseLevel("Level 4.5")).toEqual({ display: "Level 4.5", numeric: 4.5 });
    expect(parseLevel("Level 1")).toEqual({ display: "Level 1", numeric: 1 });
    expect(parseLevel("Level")).toBeNull(); // garbage row in the real export
    expect(parseLevel("Level 11")).toBeNull();
    expect(parseLevel("4")).toBeNull();
  });

  it("classifies status: archived > expired > active > uncertain", () => {
    expect(classifyStatus("2025-01-01", "General Qualification", "2026-09-23")).toBe("OFFICIAL_EXPIRED");
    expect(classifyStatus("2028-01-01", "General Qualification", "2026-09-23")).toBe("OFFICIAL_ACTIVE");
    expect(classifyStatus("2028-01-01", "Withdrawn Qualification", "2026-09-23")).toBe("OFFICIAL_ARCHIVED");
    // Missing expiry is NOT assumed valid forever (Phase 6).
    expect(classifyStatus(null, "General Qualification", "2026-09-23")).toBe("OFFICIAL_UNCERTAIN");
    // Boundary: valid_till == today is still active.
    expect(classifyStatus("2026-09-23", null, "2026-09-23")).toBe("OFFICIAL_ACTIVE");
  });
});

describe("NQR normalizeRow validation (Phase 18)", () => {
  const baseRow = {
    Title: "Test Qualification",
    Code: "QG-99-XX-00001-2025-V1-TEST",
    Description: "A test qualification.",
    "Sector Name": "Test Sector",
    Level: "Level 3",
    "Maximum Notational Hours": "300 Hours",
    "Minimum Notational Hours": "300 Hours",
    Version: "V1",
    "Originally Approved": "01 Jan 2025",
    "Valid Till": "01 Jan 2028",
    "Awarding Body": "Test SSC",
    "Certifying Bodies": "Test SSC",
    "Proposed Occupation": "Test Worker",
    "Progression Pathway": "Senior Test Worker",
    "Qualifcation Type": "General Qualification",
    "Adopted Qualifcation": "N.A.",
    "Training Delivery Hours": '{"Theory":"100","Practical":"200"}',
    __page_id: "99999",
  };

  it("normalizes a fully valid official row with provenance", () => {
    const rec = normalizeRow(baseRow);
    expect(rec.import_errors).toEqual([]);
    expect(rec.qualification_code).toBe("QG-99-XX-00001-2025-V1-TEST");
    expect(rec.nsqf_level_display).toBe("Level 3");
    expect(rec.nsqf_level_numeric).toBe(3);
    expect(rec.notional_hours_max).toBe(300);
    expect(rec.valid_till).toBe("2028-01-01");
    expect(rec.verification_status).toBe("OFFICIAL_ACTIVE");
    expect(rec.source).toBe("NCVET_NQR");
    expect(rec.source_url).toBe("https://www.nqr.gov.in/qualifications/99999");
    expect(rec.source_record_id).toBe("99999");
    expect(rec.raw_source_hash).toMatch(/^[0-9a-f]{8}$/);
    expect(rec.adopted_qualification).toBeNull(); // N.A. → null
  });

  it("rejects missing title / code / level / page id with explicit errors", () => {
    expect(normalizeRow({ ...baseRow, Title: " " }).import_errors).toContain("missing title");
    expect(normalizeRow({ ...baseRow, Code: "" }).import_errors).toContain("missing official code");
    expect(normalizeRow({ ...baseRow, Level: "Level" }).import_errors).toContainEqual(
      expect.stringContaining("invalid NSQF level"),
    );
    const noPage = normalizeRow({ ...baseRow, __page_id: "" });
    expect(noPage.import_errors).toContain("missing NQR page id (source_record_id)");
  });

  it("flags impossible durations and date order instead of importing silently", () => {
    expect(normalizeRow({ ...baseRow, "Minimum Notational Hours": "900 Hours" }).import_errors).toContain(
      "min notional hours exceed max",
    );
    expect(
      normalizeRow({ ...baseRow, "Originally Approved": "01 Jan 2029" }).import_errors,
    ).toContain("approval date after valid_till");
    expect(normalizeRow({ ...baseRow, "Valid Till": "sometime" }).import_errors).toContainEqual(
      expect.stringContaining("invalid valid_till date"),
    );
  });

  it("treats records with any validation error as not currently valid", () => {
    const bad = normalizeRow({ ...baseRow, Level: "Level" });
    expect(bad.import_errors.length).toBeGreaterThan(0);
    // A record with an invalid level has null level and cannot pass the gate.
    expect(bad.nsqf_level_numeric).toBeNull();
  });

  it("counts real rejected/active/expired numbers in the import report", () => {
    const recs = [
      normalizeRow(baseRow),
      // Expired-but-coherent record: approval predates expiry.
      normalizeRow({
        ...baseRow,
        Code: "Q2",
        __page_id: "2",
        "Originally Approved": "01 Jan 2019",
        "Valid Till": "01 Jan 2020",
      }),
      normalizeRow({ ...baseRow, Code: "Q3", __page_id: "3", Level: "bad" }),
    ];
    const rep = buildImportReport(recs);
    expect(rep.counts.total).toBe(3);
    expect(rep.counts.valid).toBe(2);
    expect(rep.counts.rejected).toBe(1);
    expect(rep.counts.active).toBe(2);
    expect(rep.counts.expired).toBe(1);
    expect(rep.errorLog).toHaveLength(1);
    expect(rep.errorLog[0].errors).toContainEqual(expect.stringContaining("invalid NSQF level"));
  });
});

// ── Phase 22: matching + eligibility ───────────────────────────────────────

const q = (over: Partial<NqrQualification> = {}): NqrQualification => ({
  code: "Q-TEST-1",
  title: "Sewing Machine Operator",
  sector: "textiles",
  sector_official: "Textile & Handloom",
  level_display: "Level 2",
  level: 2,
  hours_max: 330,
  hours_min: 330,
  valid_till: "2028-01-01",
  awarding_body: "Textile Sector Skill Council",
  occupation: "Sewing Machine Operator",
  source_url: "https://www.nqr.gov.in/qualifications/1",
  raw_source_hash: "abcd1234",
  ...over,
});

describe("NQR matching (Phase 9) — explainable", () => {
  const profile = emptyProfile("en");
  profile.current_occupation = "tailor";
  profile.skills = ["stitching", "garment_fitting"];
  // The user's own aspiration words are the lexical bridge to official titles
  // (a tailor saying "sewing" matches the official "Sewing Machine Operator").
  profile.interests = ["sewing"];

  it("scores livelihood + skill alignment and explains why", () => {
    const m = scoreNqrQualification(profile, q());
    expect(m.score).toBeGreaterThan(0);
    const ids = m.reasons.map((r) => r.id);
    expect(ids).toContain("nqrLivelihoodMatch");
    expect(ids).toContain("nqrSkillTitleMatch");
    expect(m.pathway).toBeNull();
    expect(m.historical).toBe(false);
  });

  it("gives no score to unrelated sectors", () => {
    const m = scoreNqrQualification(profile, q({ sector_official: "Mining", title: "Mine Supervisor", occupation: null }));
    expect(m.reasons.map((r) => r.id)).not.toContain("nqrLivelihoodMatch");
    expect(m.score).toBeLessThan(20); // below the recommendation threshold
  });

  it("demotes but does not hide education-ineligible records with a pathway note", () => {
    const senior = scoreNqrQualification(profile, q({ title: "Senior Data Analyst", level: 5, level_display: "Level 5", occupation: "Data Analyst" }));
    expect(senior.pathway).not.toBeNull();
    expect(senior.pathway!.blocker).toBe("education");
    // Score must be demoted below direct-recommendation range.
    const direct = scoreNqrQualification(profile, q());
    expect(senior.score).toBeLessThan(direct.score);
  });

  it("never recommends records without a parsable NSQF level", () => {
    const out = recommendNqrQualifications(profile, [q({ level: null, level_display: "" })]);
    expect(out).toHaveLength(0);
  });

  it("ranks and limits with a minimum score threshold", () => {
    const pool = [q(), q({ code: "Q-2", title: "Completely Unrelated Thing", sector_official: "Mining", occupation: null })];
    const out = recommendNqrQualifications(profile, pool, { limit: 1, minScore: 20 });
    expect(out).toHaveLength(1);
    expect(out[0].qualification.code).toBe("Q-TEST-1");
  });

  it("maps only genuine sector equivalences (no invented mappings)", () => {
    expect(NQR_SECTOR_MAP["Textile & Handloom"]).toBe("textiles");
    expect(NQR_SECTOR_MAP["Beauty & Wellness"]).toBe("beauty");
    expect(NQR_SECTOR_MAP["Mining"]).toBeUndefined();
  });
});

// ── Phase 6: active/expired gating ─────────────────────────────────────────

describe("NQR validity gate (Phase 6)", () => {
  it("accepts only OFFICIAL_ACTIVE with a current valid_till", () => {
    expect(isCurrentlyValidQualification({ verification_status: "OFFICIAL_ACTIVE", valid_till: "2099-01-01" })).toBe(true);
    expect(isCurrentlyValidQualification({ verification_status: "OFFICIAL_ACTIVE", valid_till: "2020-01-01" })).toBe(false);
    expect(isCurrentlyValidQualification({ verification_status: "OFFICIAL_EXPIRED", valid_till: "2099-01-01" })).toBe(false);
    expect(isCurrentlyValidQualification({ verification_status: "OFFICIAL_ARCHIVED", valid_till: "2099-01-01" })).toBe(false);
    expect(isCurrentlyValidQualification({ verification_status: "OFFICIAL_UNCERTAIN", valid_till: null })).toBe(false);
    expect(isCurrentlyValidQualification({ verification_status: "PROTOTYPE", valid_till: null })).toBe(false);
  });
});

// ── Phase 8/21/24: data layer + snapshot integrity ────────────────────────

describe("NQR snapshot integrity (committed official data)", () => {
  it("is a real generated snapshot with provenance metadata", () => {
    expect(snapshot.source).toBe("NCVET_NQR");
    expect(snapshot.count).toBe(snapshot.records.length);
    expect(snapshot.count).toBeGreaterThan(500);
    expect(snapshot.source_note).toContain("nqr.gov.in");
    expect(snapshot.generated_at).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it("every snapshot record is OFFICIAL-quality with full provenance", () => {
    for (const r of snapshot.records) {
      expect(r.source_url).toMatch(/^https:\/\/www\.nqr\.gov\.in\/qualifications\/\d+$/);
      expect(String(r.code)).toBeTruthy();
      expect(String(r.title)).toBeTruthy();
      expect(r.level).toBeGreaterThan(0);
      expect(r.valid_till).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      // All snapshot records were active at generation; guard against drift.
      expect(String(r.valid_till) >= snapshot.generated_at.slice(0, 10)).toBe(true);
      expect(r.raw_source_hash).toMatch(/^[0-9a-f]{8}$/);
    }
  });

  it("curated subset stays within one official sector vocabulary", () => {
    const sectors = new Set(snapshot.records.map((r) => r.sector_official));
    for (const s of sectors) {
      expect(Object.keys(NQR_SECTOR_MAP)).toContain(s as string);
    }
  });

  it("browser layer falls back honestly (no fake live connectivity)", () => {
    expect(dataLayer).toContain('"static_snapshot"');
    expect(dataLayer).toContain('"supabase_official"');
    expect(dataLayer).toContain('"none"');
    expect(dataLayer).toContain("NCVET_NQR");
  });
});

// ── Phase 19: security invariants of the migration ────────────────────────

describe("NQR migration security (Phase 19)", () => {
  it("enables RLS with no write policies (service-role-only writes)", () => {
    expect(migration).toMatch(/alter table public\.nqr_qualifications\s+enable row level security/);
    expect(migration).toMatch(/alter table public\.nqr_import_runs\s+enable row level security/);
    // No create policy statements at all on the NQR tables.
    expect(migration).not.toMatch(/create policy[^;]*on public\.nqr_/);
  });

  it("revokes base-table access and exposes only the anonymized view", () => {
    expect(migration).toMatch(/revoke all on public\.nqr_qualifications from anon, authenticated/);
    expect(migration).toMatch(/grant select on public\.nqr_qualification_public to anon, authenticated/);
    expect(migration).toMatch(/security_invoker = true/);
  });

  it("nqr_admin_summary is SECURITY DEFINER, admin-gated, pinned search_path", () => {
    const fn = migration.slice(migration.indexOf("function public.nqr_admin_summary()"));
    const block = fn.slice(0, 2500);
    expect(block).toContain("security definer");
    expect(block).toContain("set search_path = public");
    expect(block).toContain("app_metadata");
    expect(block).toContain("raise exception 'admin role required'");
    expect(block).toMatch(/revoke all on function public\.nqr_admin_summary\(\) from public, anon, authenticated/);
  });

  it("provenance columns are NOT NULL and status is enum-constrained", () => {
    expect(migration).toMatch(/source\s+text not null default 'NCVET_NQR'/);
    expect(migration).toMatch(/source_url\s+text not null/);
    expect(migration).toMatch(/source_record_id\s+text not null/);
    expect(migration).toMatch(/raw_source_hash\s+text not null/);
    expect(migration).toMatch(/verification_status in\s*\n?\s*\('OFFICIAL_ACTIVE','OFFICIAL_EXPIRED','OFFICIAL_ARCHIVED',/);
  });

  it("importer requires service-role env vars and never a VITE_ variable", () => {
    expect(importer).toContain("SUPABASE_SERVICE_ROLE_KEY");
    expect(importer).not.toContain("VITE_SUPABASE_SERVICE_ROLE_KEY");
    expect(importer).toMatch(/SUPABASE_URL \?\? process\.env\.VITE_SUPABASE_URL/);
  });

  it("importer targets only the official NQR origin", () => {
    expect(importer).toContain("https://www.nqr.gov.in");
    expect(importer).not.toMatch(/http:\/\/(?!localhost)/);
    expect(importer).toContain("User-Agent");
  });
});

// ── Phase 23: regression — existing prototype pipeline untouched ──────────

describe("NQR regression — existing pipeline still works", () => {
  it("prototype opportunity engine still produces explainable matches", () => {
    const profile = emptyProfile("en");
    profile.current_occupation = "tailor";
    profile.skills = ["stitching"];
    const courses = [
      {
        id: "gc1", name: "Sewing Machine Operator", sector: "textiles" as const,
        nsqf_level: 2, duration_months: 3, provider: "X", district: "Nagpur",
        state: "Maharashtra", seats_left: 10, stipend_monthly: 1000,
        languages: ["hi"], keywords: ["stitching"],
      },
    ];
    const matches = recommendOpportunities(profile, courses, 3);
    expect(matches).toHaveLength(1);
    expect(matches[0].reasons.length).toBeGreaterThan(0);
  });

  it("utility helpers are stable", () => {
    expect(contentHash("abc")).toBe(contentHash("abc"));
    expect(contentHash("abc")).not.toBe(contentHash("abd"));
    expect(cleanText("A&amp;B\uFB01x")).toBe("A&Bfix");
    expect(parseSharedStrings("<si><t>Hello</t></si>")).toEqual(["Hello"]);
  });

  it("xlsx reader handles the official export shape", () => {
    // Minimal single-sheet workbook bytes (stored entry) — parser-level check.
    const ss = parseSharedStrings('<si><t>Title</t></si><si><t>Val</t></si>');
    expect(ss).toEqual(["Title", "Val"]);
  });
});
