/**
 * Official NQR data layer (Phase 20/21/24) — separate from beneficiary data
 * and from the prototype catalog. Layers, in priority order:
 *
 *   1. Supabase table `nqr_qualifications` (admin-imported via
 *      scripts/nqr-import.mjs --db; anonymized public read under RLS)
 *   2. Static official snapshot public/nqr/official-active.json (generated by
 *      the importer from the official NQR export; ships with the PWA)
 *   3. No official data → the existing prototype pipeline answers alone
 *      (unchanged), and the UI says so.
 *
 * Every match result carries `data_source` so the UI can label exactly where
 * a recommendation came from — never faking live connectivity (Phase 24).
 */
import { hasSupabase, supabase } from "./supabase";
import type { LivelihoodProfile } from "../../supabase/functions/_shared/extract";
import {
  recommendNqrQualifications,
  type NqrQualification,
  type NqrMatch,
} from "../../supabase/functions/_shared/nqrmatch";

export type NqrDataSource = "supabase_official" | "static_snapshot" | "none";

export interface NqrRecommendation extends NqrMatch {
  data_source: NqrDataSource;
}

/** Manifest of the committed static snapshot (generated by the importer). */
export interface NqrSnapshotMeta {
  generated_at: string;
  source: "NCVET_NQR";
  count: number;
  source_note: string;
}

const SNAPSHOT_URL = "nqr/official-active.json";

let snapshotCache: { meta: NqrSnapshotMeta; records: NqrQualification[] } | null = null;

/**
 * Load the static official snapshot (fetched, not bundled: keeps the main
 * chunk lean and lets the PWA cache it as a versioned asset). Returns null
 * when unavailable (e.g. fetch failure) — callers fall back cleanly.
 */
export async function loadNqrSnapshot(): Promise<{ meta: NqrSnapshotMeta; records: NqrQualification[] } | null> {
  if (snapshotCache) return snapshotCache;
  try {
    const res = await fetch(SNAPSHOT_URL);
    if (!res.ok) return null;
    const json = (await res.json()) as Partial<NqrSnapshotMeta> & {
      records?: NqrQualification[];
      source?: string;
    };
    if (json?.source !== "NCVET_NQR" || !Array.isArray(json.records)) return null;
    const meta: NqrSnapshotMeta = {
      generated_at: String(json.generated_at ?? ""),
      source: "NCVET_NQR",
      count: Number(json.count ?? json.records.length),
      source_note: String(json.source_note ?? ""),
    };
    snapshotCache = { meta, records: json.records };
    return snapshotCache;
  } catch {
    return null;
  }
}

async function loadFromSupabase(): Promise<NqrQualification[] | null> {
  if (!hasSupabase || !supabase) return null;
  try {
    // Anonymized public read: the view/table exposes qualification facts
    // only (no beneficiary data, Phase 20). Expiry re-checked client-side
    // against valid_till so a stale cache cannot resurface expired rows.
    const { data, error } = await supabase
      .from("nqr_qualifications")
      .select(
        "qualification_code, qualification_title, sector_official, nsqf_level_display, nsqf_level_numeric, notional_hours_max, notional_hours_min, valid_till, awarding_body, proposed_occupation, source_url, raw_source_hash",
      )
      .eq("verification_status", "OFFICIAL_ACTIVE")
      .limit(2000);
    if (error || !data || data.length === 0) return null;
    return data.map((d) => ({
      code: String(d.qualification_code),
      title: String(d.qualification_title),
      sector: null,
      sector_official: String(d.sector_official ?? ""),
      level_display: String(d.nsqf_level_display ?? ""),
      level: d.nsqf_level_numeric === null ? null : Number(d.nsqf_level_numeric),
      hours_max: d.notional_hours_max === null ? null : Number(d.notional_hours_max),
      hours_min: d.notional_hours_min === null ? null : Number(d.notional_hours_min),
      valid_till: d.valid_till === null ? null : String(d.valid_till),
      awarding_body: d.awarding_body === null ? null : String(d.awarding_body),
      occupation: d.proposed_occupation === null ? null : String(d.proposed_occupation),
      source_url: String(d.source_url ?? ""),
      raw_source_hash: String(d.raw_source_hash ?? ""),
    }));
  } catch {
    return null;
  }
}

export interface NqrResult {
  matches: NqrRecommendation[];
  /** Where the data came from — the UI labels this honestly (Phase 24). */
  source: NqrDataSource;
  meta: NqrSnapshotMeta | null;
}

/**
 * Full resolution chain (Phase 24): LIVE (Supabase) → CACHED (static
 * snapshot) → none. The existing prototype pipeline is untouched and
 * continues to work when this returns { matches: [], source: "none" }.
 */
export async function fetchNqrRecommendations(
  profile: LivelihoodProfile,
  limit = 4,
): Promise<NqrResult> {
  // 1. Live official data (admin-synced).
  const fromDb = await loadFromSupabase();
  if (fromDb && fromDb.length > 0) {
    return {
      matches: recommendNqrQualifications(profile, fromDb, { limit }).map((m) => ({
        ...m,
        data_source: "supabase_official" as const,
      })),
      source: "supabase_official",
      meta: null,
    };
  }

  // 2. Committed static snapshot generated from the official export.
  const snap = await loadNqrSnapshot();
  if (snap) {
    return {
      matches: recommendNqrQualifications(profile, snap.records, { limit }).map((m) => ({
        ...m,
        data_source: "static_snapshot" as const,
      })),
      source: "static_snapshot",
      meta: snap.meta,
    };
  }

  // 3. Honest fallback: no official data available.
  return { matches: [], source: "none", meta: null };
}
